### ISSUE TITLE
Create "add session" button in Client Profile View

### ISSUE THREAD

**Issue by justindi15** [justindi15/teatree#1]
Adding session button uses the current client's id in the input field for client id.

**Comment by gabydi106** [comment]
# Expected behaviour:

1. Click **"Log session"** from ~/clients/ or ~/clients/2/show should go to ~/sessions/new
2. Client ID field should be pre-filled with the Client ID to associate the session record with
3. Client ID field should be hidden
4. Datetime field should be read only (not drop down, and cannot be changed)
5. Upon save, **redirect_to client_path(@session.client_id), notice: 'Session was successfully created.'** with green banner on top

**Comment by gabydi106** [comment]
![image](https://user-images.githubusercontent.com/7362062/38713214-ed0a4d4a-3e84-11e8-97d2-de4277cdbe27.png)
![image](https://user-images.githubusercontent.com/7362062/38713243-10dca416-3e85-11e8-9fd8-ba81dd108163.png)


![image](https://user-images.githubusercontent.com/7362062/38713345-9283d566-3e85-11e8-8a2d-b361208dad92.png)

![image](https://user-images.githubusercontent.com/7362062/38713395-ce1452d6-3e85-11e8-80d6-6e3b4c2af4ed.png)

**Comment by gabydi106** [comment]
UPDATE: **Log sessions** button works; need to fix show/delete sessions for Therapy Log (minor)

**Comment by gabydi106** [comment]
UPDATE: all done, looks good so far. Closing this issue. 👍 
@justindi15  Good work on the back end!
